sudo: false
language: node_js
node_js:
    - stable
    - '0.12'
install:
    - export NODE_ENV=development
    - npm install
    - npm uninstall gulp-sass
    - npm install gulp-sass@2
    - npm rebuild node-sass
    - cp _config/task.sass.js test/mock-project/_config/task.sass.js
    - cp package.json test/mock-project/package.json
    - cd test/mock-project
    - npm install
    - npm uninstall gulp-sass
    - npm install gulp-sass@2
    - npm rebuild node-sass
    - npm install mocha -g
    - npm install gulp-cli -g
    - npm install gulp
    - cd ../..
script:
    - mocha
cache:
  directories:
    - node_modules
    - test/mock-project/node_modules
git:
  depth: 1