sudo: false
language: node_js
node_js:
    - stable
    - '0.12'
install:
    - npm install --ignore-scripts
    - npm rebuild node-sass
    - npm install -g mocha
    - cp _config/task.sass.js test/mock-project/_config/task.sass.js
    - cp package.json test/mock-project/package.json
    - cd test/mock-project
    - npm install
    - cd ..
script:
    - mocha
cache:
  directories:
    - node_modules
git:
  depth: 1
