sudo: false
language: node_js
node_js:
    - stable
    - '0.12'
install:
    # Copy over module config and package into mock project directory
    - cp _config/task.sass.js test/mock-project/_config/task.sass.js
    - cp package.json test/mock-project/package.json
    # Go into mock-project directory
    - cd test/mock-project
    # Get all module dependencies (don't run post install)
    - npm install --ignore-scripts
    # Manually build node-sass (--ignore-scripts cancels this)
    - npm rebuild node-sass
    # Go back to the module root
    - cd ../..
script:
    # Run tests
    - mocha
cache:
  directories:
    - test/mock-project/node_modules
git:
  depth: 1