sudo: false
language: node_js
env:
    - NODE_ENV=development
install:
    - npm install
script:
    - mocha
    - npm run lint
cache:
  directories:
    - node_modules
    - test/mock-project/node_modules
notifications:
    email: false
node_js:
    - '5.1'
    - '4.4'
    - '0.12.2'
before_install:
    - npm i -g npm@^2.0.0
before_script:
    - npm prune
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
  - bash <(curl -s https://codecov.io/bash)
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
